name: g4mp2_ml
channels:
  - openbabel
  - conda-forge
  - defaults
dependencies:
  - python==3.7.*
  - numpy==1.16.*
  - pymatgen==2019.7.2
  - pandas==0.23.*
  - scikit-learn==0.20.0
  - pytorch==0.4.1
  - matplotlib==3.*
  - openbabel==2.4.1
  - jupyterlab
  - pytest
  - pip
  - pip:
    - mdf_forge
    - dlhub_sdk
    - globus_sdk
    - git+https://github.com/WardLT/schnetpack.git@d9439d2#egg=schnetpack
    - git+https://github.com/WardLT/qml.git@change_xyz#egg=qml
    - -e.
